# Default config.
# Can be overridden by
# `~/.config.yaml` if it exists.
# In turn, this may be overridden by
# `lintify.yaml` file, next to `pyproject.toml`

# raw | frame
theme: 'frame'

# may be overridden by --watch-dir cli option
watch_dir: './'

files:
  - '*.py'

linters:
  # - 'autoflake --remove-all-unused-imports --in-place {path}'
  # - ['flake8 {path}', 'mypy {path}']
